<a href="https://colab.research.google.com/github/kesavan1994/NumpyAssingment/blob/main/Copy_of_Numpy_tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [269]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [270]:
print(np.__version__)
print(np.show_config)

1.21.6
<function show at 0x7f2ca9822670>


#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [271]:
import numpy as np
a=np.zeros(10)
a

array([0., 0., 0., ..., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [272]:
print(a.size)
print(a.itemsize)

10
8


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [273]:
np.arange(10,50)

array([10, 11, 12, ..., 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [274]:
a=[1,2,3,4,5]
a[::-1]

[5, 4, 3, 2, 1]

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [275]:
a=np.arange(0,9)
a.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [276]:
a=[1,2,0,0,4,0]
np.nonzero(a)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [277]:
a=np.eye(3,3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [278]:
b=np.random.random((3,3,3))
b

array([[[0.15901159, 0.90529534, 0.51301839],
        [0.96363836, 0.49191274, 0.08941276],
        [0.0918445 , 0.32681586, 0.0089041 ]],

       [[0.42873652, 0.79011043, 0.85128237],
        [0.40837869, 0.32446648, 0.23385261],
        [0.30321302, 0.2836246 , 0.6765078 ]],

       [[0.44406165, 0.94791386, 0.89089825],
        [0.00774343, 0.95242709, 0.70071713],
        [0.23614441, 0.7073955 , 0.54927634]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [279]:
ra=np.random.randint(0,10,100)
print(ra.reshape(10,10))
print('min:', ra.min(), 'max:' ,ra.max())

[[8 6 2 ... 1 6 4]
 [0 2 7 ... 5 6 2]
 [2 2 4 ... 2 0 8]
 ...
 [5 5 1 ... 2 8 0]
 [7 4 4 ... 3 0 8]
 [2 9 4 ... 6 7 7]]
min: 0 max: 9


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [280]:
import numpy as np

n=np.random.randint(1,20,30)
print(n)

print('mean:',n.mean())

[ 7  3  2 ...  1  2 12]
mean: 10.366666666666667


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [281]:
a=np.zeros(9).reshape(3,3)
a=np.pad(a, pad_width=1, mode='constant',
               constant_values=1)
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [282]:
a=np.ones(9).reshape(3,3)

a=np.pad(a, pad_width=1, mode='constant',
               constant_values=0)
print(a)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [283]:
#nan
#False
#False
#nan
#False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [284]:
import numpy as np
a=np.arange(1,5)
np.diag(a,k=-1)


array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [285]:
a=np.zeros((8,8),dtype=int)
a[1::2,::2]=1
a[::2,1::2]=1
a

array([[0, 1, 0, ..., 1, 0, 1],
       [1, 0, 1, ..., 0, 1, 0],
       [0, 1, 0, ..., 1, 0, 1],
       ...,
       [1, 0, 1, ..., 0, 1, 0],
       [0, 1, 0, ..., 1, 0, 1],
       [1, 0, 1, ..., 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [286]:
a=np.random.random((6,7,8))
np.unravel_index(100,a.shape)


(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [287]:
a=np.array([[0,1],[1,0]])
np.tile(a,(4,4))

array([[0, 1, 0, ..., 1, 0, 1],
       [1, 0, 1, ..., 0, 1, 0],
       [0, 1, 0, ..., 1, 0, 1],
       ...,
       [1, 0, 1, ..., 0, 1, 0],
       [0, 1, 0, ..., 1, 0, 1],
       [1, 0, 1, ..., 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [288]:
a=np.random.random((5,5))
min_a,max_a = a.min(),a.max()
c=(a-min_a)/(max_a-min_a)
c

array([[0.90454492, 0.8379552 , 0.97471976, 0.3177334 , 0.12740415],
       [0.55821452, 0.82898039, 0.        , 0.46973195, 0.41462282],
       [0.10747783, 1.        , 0.41905219, 0.40857987, 0.52866108],
       [0.95564432, 0.24462977, 0.68328512, 0.80119457, 0.72054513],
       [0.50024276, 0.33871998, 0.12129511, 0.78408936, 0.11224618]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [289]:

np.dot(np.random.randint(1,3,(5,3)),np.ones((3,2)))

array([[4., 4.],
       [5., 5.],
       [5., 5.],
       [5., 5.],
       [5., 5.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [290]:
a=np.random.randint(1,10,10)
print(a)
np.where((a>3) & (a<=8),a,'')

[5 1 3 ... 6 8 5]


array(['5', '', '', ..., '6', '8', '5'], dtype='<U21')

#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [291]:
9
10

10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [292]:
True
False




False

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [293]:
# Nan 
# runtime error because of floor divion not divisiable by zero

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [294]:
a=np.random.randn(5)
#print(a.uniform())
print(np.copysign(a))

TypeError: ignored

#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [ ]:
a=[1,3,5,6,7]
b=[2,4,6,8]
np.intersect1d(a,b)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [ ]:
print(np.datetime64(19364,'D'))
print(np.datetime64(19365,'D'))
print(np.datetime64(19366,'D'))

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [ ]:
print(np.datetime64(16983,'D'))
a=(np.datetime64(16983,'D'))
np.arange(a,31,)

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [ ]:
a=10
b=5
np.multiply((np.add(a,b)),(np.divide(-a,2)))

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [ ]:
from typing_extensions import assert_type
import numpy as np
a=np.random.randn(5)
print(a)
print(np.floor(a))
print(np.ceil(a))
print(a.astype(int))
print(np.trunc(a))


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [ ]:
b=np.ones((5,5))
a=np.arange(5)
np.multiply(b,a)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [ ]:
iter=[x+x for x in range(10)]
np.fromiter(iter,int)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [ ]:
np.linspace(0,1,10)

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [ ]:
sorted(np.random.randint(1,8,10))


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [ ]:
X = np.arange(8).reshape((2,2,2))
print(X)
np.add.reduce(X,2)

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [ ]:
a=np.random.random(5)
b=np.random.random(5)
print(a,b)
print(np.allclose(a,b))
print(np.array_equal(a,b))


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [ ]:
z=np.linspace(1,5,3)
z.flags.writeable=False
z[0]=1

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [ ]:
a=np.random.random(20).reshape(10,2)
x,y=a[:,0],a[:,1]
r=np.sqrt(x**2,y**2)
ar=np.arctan(y,x)
print(r)
print(ar)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [ ]:
a=np.arange(1,10)

a[np.argmax(a)]=0
a

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [ ]:
a=np.ones((5,5),[('x',float),('y',float)])
a['x'],a['y']=np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
a

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [ ]:
a=np.array([1,2,3,4])
b=np.array([5,6,7])

d=np.subtract.outer(a,b)
z=1.0/d
z


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [ ]:
print(np.iinfo(np.int8).min)
for i in [np.int8,np.int32,np.int64]:
  print(np.iinfo(i).min)
  print(np.iinfo(i).max)
for j in [np.float16,np.float64] :
  print(np.finfo(j).min)
  print(np.finfo(j).max)
  print(np.finfo(j).eps)

#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [ ]:
np.set_printoptions(threshold=0)
np.zeros((5,5))



#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [ ]:
a=np.random.randint(1,5,6)
a[np.argmin(a)]

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [ ]:
a=np.ones(10,[('position',[('x',float,1),('y',float,1)]),
                    ('color',[('r',int,1),('g',int,1),('b',int,1)])])

print(a)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [ ]:
a=np.ones((100,2))
np.sqrt(np.atleast_2d(a).T)


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [ ]:
a=np.random.randn(5)
print(a.astype(np.float32))
print(a.astype(np.int32))

#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

> Indented block


(**hint**: np.ndenumerate, np.ndindex)

In [ ]:
import numpy as np
a=np.arange(9).reshape(3,3)
for index,value in np.ndenumerate(a):
  print(index,value)
for index in np.ndindex(a.shape):
  print(index,a[index])


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [ ]:
x,y=np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))
np.exp(x,y)

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [ ]:
a=np.random.random(9)
print(a)
print()
print(np.random.choice(a))
print(np.put(a,[2,0],[11,22]))

#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [ ]:
n=np.random.random(9).reshape(3,3)
print(n)
n-n.mean(axis=1,keepdims=False)

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [ ]:
import numpy as np

a=np.arange(0,9).reshape(3,3)
print(a)
print(np.argsort(a,axis=0,kind='heapsort'))
# np.take_along_axis(a,n,axis=0)

#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [ ]:
a=np.random.randint(0,3,(3,10))
print((~a.any(axis=0)).any())

#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [ ]:
n=np.arange(0,10)
N=2.5
m=n.flat[np.abs(N-n).argmin()]
print(m)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [ ]:
x=np.random.randint(1,4,(1,3))
y=np.random.randint(10,14,(3,1))
print(x,y)
for i,j in np.nditer([x,y],order='C'):
  print(i+j)

#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [ ]:
class name:

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [ ]:
a=np.ones(10)
print(a)
B=np.random.randint(0,len(a),10)
z=np.bincount(B,minlength=len(a))
z

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [ ]:
a=np.arange(5)
np.bincount(a,minlength=8)


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [ ]:
import numpy as np

I=np.random.randint(0,2,(5,5)).astype(np.ubyte)
D=I[...,0]*256*256+I[...,1]*256+I[...,2]
n=len(D)
print(np.unique(I))

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [ ]:
N=np.random.randint(1,10,(3,4,3,4))
sum=N.reshape(N.shape)
N.sum(axis=(-2,-1))


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [ ]:
D=np.arange(1,10,5)
S=np.arange(1,10,5)
np.bincount(S,weights=D)

#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [ ]:
A=np.random.randint(1,5,(5,5))
B=np.random.randint(1,5,(5,5))
np.diag(np.dot(A,B))

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [ ]:
a=[1,2,3,4,5]
z=np.zeros(len(a)+(len(a)-1)*3)
z[::4]=a
z

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [ ]:
a=np.ones((5,5,3))
b=3*np.ones((5,5))
print(a*b[:,:,None])

#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [ ]:
a=np.random.randint(1,6,(3,3))
print(a)
a[[0,1]]=a[[1,0]]
a

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [ ]:
a=np.random.randint(1,50,(10,3))

b=np.roll(a.repeat(2,axis=1),-1,axis=1)
b=b.reshape(len(b)*3,2)
b=np.sort(b,axis=1)
b=b.view(dtype=[('F0',b.dtype),('f1',b.dtype)])
z=np.unique(b)
print(z)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [ ]:
c=np.bincount([1,1,3,4,4,6,7])
z=np.repeat(np.arange(len(c)),c)
z

#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [ ]:
a=np.arange(0,10)

c[4:]=c[4:]-c[:-4]
c[4-1:]/4

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [ ]:
from numpy.lib import stride_tricks
a=np.arange(0,10)
s=(a.size-3+1,3)
st=(a.itemsize,a.itemsize)
c=np.lib.stride_tricks.as_strided(a,shape=s,strides=st)
c

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [ ]:
Z = np.random.randint(0,2,100)
print ('original: ')
print (Z)
print('Negating a boolean: ')
print(np.logical_not(Z, out=Z))


Z = np.random.uniform(-1.0,1.0,10)
print ('original: ')
print (Z)
print ('Change the sign of float inplace: ')
print(np.negative(Z, out=Z))

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
a=np.arange(1,15)
s=(a.size-4+1,4)
st=(a.itemsize,a.itemsize)
c=np.lib.stride_tricks.as_strided(a,shape=s,strides=st)
print(a)
print(c)

#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [ ]:
a=np.random.randint(1,10,(4,4))
s,v,d=np.linalg.svd(a)
np.sum(v> 1e-10)

#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [ ]:
a=np.random.randint(1,10,20)
print(a)
np.bincount(a).argmax()

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
a=np.random.randint(1,15,(10,10))
s=1+a.shape[0]-3
t=1+a.shape[1]-3

c=np.lib.stride_tricks.as_strided(a,shape=(s,t,3,3),strides=a.strides+a.strides)
c

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [ ]:
a=np.ones((16,16))
c=np.add.reduceat(np.add.reduceat(a,np.arange(0,a.shape[0],4),axis=0),np.arange(0,a.shape[1],4),axis=1)
c

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [ ]:
a=np.arange(1000)
np.random.shuffle(a)
n=5
print(a[np.argsort(a)[-n:]])
print(a[np.argpartition(-a,n)[:n]])

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [ ]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
R

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [ ]:
r=np.random.rand(5)
print(r)
%timeit np.power(r,3)
%timeit r*r*r
%timeit np.einsum('ss',r,r,r)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [ ]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))
print(A)
print(B)
C = (A[..., np.newaxis, np.newaxis] == B)

rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print(rows)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [ ]:
a=np.random.randint(0,3,(10,3))
b=np.logical_and.reduce(a[:,1:]==a[:,:-1],axis=1)
z=a[~b]
print(a)
print(z)

#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [324]:
a=np.arange(4)
b=np.arange(5,9)
np.einsum('i->',a)#Sum
np.einsum('i,j->ij',a,b)#outer
np.einsum('i,i->i', a, b)#Multiply

array([ 0,  6, 14, 24])

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)